services:
  - type: web
    name: drum-school-management
    runtime: node
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npx prisma migrate deploy && npm run start
    envVars:
      - key: DATABASE_URL
        fromValue: ${DATABASE_URL}
      - key: DIRECT_URL
        fromValue: ${DIRECT_URL}
      - key: NEXTAUTH_URL
        fromValue: ${RENDER_EXTERNAL_URL}
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NODE_VERSION
        value: 18
