services:
  - type: static
    name: khora-static
    buildCommand: npm install && npm run build
    publishPath: out
    envVars:
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: NODE_VERSION
        value: 18
